### ISSUE TITLE
Should check if file is a directory rather than `basename(fp) === 'package.json'`

### ISSUE THREAD

**Issue by stevemao** [sindresorhus/read-pkg#2]
https://github.com/sindresorhus/read-pkg/blob/master/index.js#L13
If it's not a directory we shouldn't then append 'package.json'.
Mainly for tests https://github.com/npm/normalize-package-data/tree/master/test/fixtures. I have a bunch of `package.json`s that are called something else.

**Comment by sindresorhus** [comment]
Sure, wanna do a PR?

**Comment by stevemao** [comment]
Yup :)
