### ISSUE TITLE
Allow sentimental versioning

### ISSUE THREAD

**Issue by binarykitchen** [sindresorhus/read-pkg#20]
This error is thrown in my project

```
Error: Invalid version: "207-alpha1-SNAPSHOT"
```

Our version in package.json is sentimental, not in semver.

In error stack trace I can see above error comes from

```
...
/node_modules/normalize-package-data/lib/normalize.js:31:15
/node_modules/webpack-babel-env-deps/node_modules/read-pkg/index.js:43:36
```

Not sure if this is related to your package or normalize-package-data. Feel free to close if I'm wrong here. 

Thanks.

**Comment by sindresorhus** [comment]
I think the package.json spec requires semver. Regardless, you should open an issue on the normalize-package-data package instead. 👍
