### ISSUE TITLE
Add a method/option to read from a string/JSON

### ISSUE THREAD

**Issue by tommy-mitchell** [sindresorhus/read-pkg#28]
Based on the title/synopsis, I expected this to also be able to normalize a file in memory. I wanted to do this for `np` (for https://github.com/sindresorhus/np/issues/88):

```js
const getPackageJsonFromLastRelease = async pkgPath => {
	const pkg = await gitUtil.readFileFromLastRelease(pkgPath);
	return readPackage(pkg);
	//=> Promise<NormalizedPackageJson>
};
```

Should `read-pkg` support this? Since `normalize-package-data` is already a dependency, adding this capability saves a user adding two dependencies instead of one.

**Comment by tommy-mitchell** [comment]
Possible signature:

```ts
import type {PackageJson} from 'type-fest';

const parsePackage = (package: PackageJson | string) => NormalizedPackageJson;
```

**Comment by sindresorhus** [comment]
> Possible signature:

👍
