### ISSUE TITLE
Enhancement: an option to avoid exception on ENOENT

### ISSUE THREAD

**Issue by zkochan** [sindresorhus/read-pkg#4]
Sometimes it is OK that a package is missing. In that cases it would be nice to get a `null` from `read-pkg` instead of an ENOENT exception.

I suggest to add `readPkg.safe()` and `readPkg.safeSync()` which will return null when no `package.json` found

Would you accept such an enhancement?

**Comment by sindresorhus** [comment]
I'm just curious why this package should handle that? Potentially any module could throw, so with this logic every package would need a `.safe()` method. What makes this one different?

**Comment by zkochan** [comment]
Yes, indeed
