### ISSUE TITLE
Please remove strip-bom & path-type

### ISSUE THREAD

**Issue by hulkish** [sindresorhus/read-pkg#6]
`read-pkg` is a very widely used package. Because of this, I'd like to suggest removal of extraneous logic. In particular:

- `strip-bom`
  - If your package is using an invalid UTF8 file format, an error will and should be thrown.
  - It is the user/dev's responsibility to use correct file formats.
- `path-type`
  - Cause an extra FS call in exchange for no real benefit.
  - Same goal can be achieved, by using `path.extname()`

**Comment by sindresorhus** [comment]
Done in v4.
